# Generated by Django 3.2.7 on 2021-10-11 06:25

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('free_consultation_request', models.BooleanField()),
                ('project_name', models.CharField(max_length=254)),
                ('project_description', models.CharField(max_length=254)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Update quote status'), ('2', 'Consultation requested'), ('3', 'Consultation booked, query closed'), ('4', 'Quote sent, query closed')], default=1, max_length=254)),
                ('query_closed', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
