# Generated by Django 3.2.7 on 2021-10-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
