# Generated by Django 3.2.7 on 2021-09-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210924_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='status',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='consultation_status',
            field=models.CharField(choices=[('1', 'No consultation requested'), ('Consultation requested', 'Consultation requested'), ('Consultation booked', 'Consultation booked')], default='Update status', max_length=254),
        ),
    ]
