# Generated by Django 3.2.7 on 2021-09-24 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210924_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='consultation_status',
            field=models.CharField(choices=[('1', 'Update consultation status'), ('2', 'No consultation requested'), ('3', 'Consultation requested'), ('4', 'Consultation booked')], default='Update status', max_length=254),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='quote_request_id',
            field=models.CharField(default=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
