# Generated by Django 3.2.7 on 2021-09-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20210924_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='request_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='consultation_status',
            field=models.CharField(blank=True, choices=[('1', 'Update consultation status'), ('2', 'No consultation requested'), ('3', 'Consultation requested'), ('4', 'Consultation booked')], default=1, max_length=254, null=True),
        ),
    ]
