# Generated by Django 3.2.7 on 2021-10-11 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_quoterequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='id',
            field=models.BigAutoField(default=uuid.UUID('0cf80452-3def-4176-9d69-318fbc0823b8'), primary_key=True, serialize=False),
        ),
    ]
