# Generated by Django 3.2.7 on 2021-10-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_quoterequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='free_consultation_request',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='project_description',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='project_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='query_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
