# Generated by Django 3.2.7 on 2021-10-04 11:57

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20211004_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='free_consultation_request',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
