# Generated by Django 3.2.7 on 2021-10-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20211004_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='consultation_status',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='query_closed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Update quote status'), ('2', 'Consultation requested'), ('3', 'Consultation booked, query closed'), ('4', 'Quote sent, query closed')], default=1, max_length=254),
        ),
    ]
