# Generated by Django 3.2.7 on 2021-10-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20211011_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='id',
            new_name='quote_request_id',
        ),
    ]
