# Generated by Django 3.2.7 on 2021-10-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_rename_id_quoterequest_quote_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='quote_request_id',
            new_name='id',
        ),
    ]
