# Generated by Django 3.2.7 on 2021-10-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_rename_quote_request_id_quoterequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='free_consultation_request',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
