# Generated by Django 3.2.7 on 2021-10-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_alter_quoterequest_free_consultation_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='free_consultation_request',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
