# Generated by Django 3.2.7 on 2021-10-07 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequest',
            old_name='account_company_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='is_digital',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='order_timeslot_confirmed',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='timeslot_option_1',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='timeslot_option_2',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='total_booking_hours',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='total_order_value',
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='county',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='order_number',
            field=models.CharField(default=1, editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='original_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='street_address1',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='town_or_city',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
