# Generated by Django 3.2.7 on 2021-10-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderrequest_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='user_profile',
        ),
    ]
