# Generated by Django 3.2.7 on 2021-10-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderlineitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequest',
            old_name='date',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='order_total',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='timeslot_option_1',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='timeslot_option_2',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
