# Generated by Django 3.2.7 on 2021-10-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20211014_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='timeslot_option_1',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='timeslot_option_2',
        ),
    ]
