# Generated by Django 3.2.7 on 2021-10-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20211014_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='timeslot_option_1',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='timeslot_option_2',
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='note',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
