# Generated by Django 3.2.7 on 2021-09-28 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.CharField(default=False, max_length=50, primary_key=True, serialize=False)),
                ('account_company_name', models.CharField(max_length=50)),
                ('timeslot_option_1', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('timeslot_option_2', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('project_name', models.CharField(max_length=254)),
                ('project_description', models.CharField(max_length=254)),
                ('is_digital', models.BooleanField(default=False)),
                ('total_booking_hours', models.CharField(max_length=254)),
                ('total_order_value', models.CharField(max_length=254)),
                ('order_status', models.CharField(choices=[('1', 'Update order status'), ('2', 'Order timeslot requested'), ('3', 'Order timeslot confirmed'), ('4', 'Timeslot meeting completed and closed')], default=1, max_length=254)),
                ('order_timeslot_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
