# Generated by Django 3.2.7 on 2021-09-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_basket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderRequest',
        ),
    ]
