# Generated by Django 3.2.7 on 2021-10-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(choices=[('Project Hours', 'Project Hours'), ('Marketing Templates', 'Marketing Templates'), ('Free consultation', 'Free consultation')], default='Project Hours', max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('is_available_guest_user', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description_1', models.CharField(blank=True, max_length=100)),
                ('description_2', models.CharField(blank=True, max_length=100)),
                ('description_3', models.CharField(blank=True, max_length=100)),
                ('description_4', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('time_allocation_mins', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('is_digital', models.BooleanField()),
                ('max_time_multiplier', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('pricing_priority', models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], decimal_places=0, default='4', max_digits=6, null=True)),
                ('category', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
