# Generated by Django 3.2.7 on 2021-10-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(choices=[('1', 'Project Hours'), ('2', 'Marketing Templates'), ('3', 'Free consultation')], default='Project Hours', max_length=254),
        ),
    ]
