# Generated by Django 3.2.7 on 2021-10-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211004_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(choices=[('Project Hours', 'Project Hours'), ('Marketing Templates', 'Marketing Templates'), ('Free consultation', 'Free consultation')], default='Project Hours', max_length=254),
        ),
    ]
