# Generated by Django 3.2.7 on 2021-10-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_time_multiplier',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_allocation_mins',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
    ]
