# Generated by Django 3.2.7 on 2021-10-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211004_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='description_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='description_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='description_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_priority',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], decimal_places=0, default='4', max_digits=6, null=True),
        ),
    ]
